name: Test JSON schema transforation in container 

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Add workspace to path
        run: |
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - name: Fetch container
        run: |
          docker pull quay.io/ebigxa/json_schema_transform
          
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install python testing deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run test script
        run: |
          run_tests.sh  
